defaults:
  - _self_
  - exp: bsd_deblurring

# logging
mode: 'map' # 'map' or 'sample'
logdir: results
log_logpzl: False
log_images: False
backprop: False
optimizer: # only when backprop=True (baseline)
  _target_: torch.optim.Adam
  lr: 0.01
