
type: deblurring
name: celeba
vae: vdvae
vae_conf: null # only for patchVDVAE
input_path: images/celeba/00280.png
sf: 4 #scale factor
kernel: kernels/9.npy
noise_lvl: 8
# temperature:
#   _target_: utils.temperature.Constant
#   T: 0.8 # temperature recommended: 0.95, 0.80, 0.60
#   name: "const_${exp.temperature.T}"
temperature:
  _target_: utils.temperature.Linear
  t_min: 0.99
  t_max: 0.8
  levels: 66
  name: "lin_${exp.temperature.t_min}_${exp.temperature.t_max}"
decoder_std: 5
maxiter: 50
sample_from_prior_after: null

scheduler:
  track: 'residual' # 'residual' or 'loss'
  patience: 10
  tol: 0.001
  beta_min: 1
  beta_max: 1
  delta_beta: 0.1